include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - test
  - build
  - prepare
  - deploy
  - release

default:
  image: node:16
  interruptible: true

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

variables:
  # Setting this variable will affect all Security templates
  # (SAST, Dependency Scanning, ...)
  SAST_EXCLUDED_ANALYZERS: "bandit, brakeman, flawfinder, gosec, kubesec, mobsf, nodejs-scan, phpcs-security-audit, pmd-apex, security-code-scan, sobelow, spotbugs"
  SAST_EXCLUDED_PATHS: &sast-excluded-path ".yarn, build, node_modules, public, /reports, /release"
  SAST_SEMGREP_METRICS: "false"
  SECURE_LOG_LEVEL: "debug"
  SECRET_DETECTION_EXCLUDED_PATHS: *sast-excluded-path
  # to disable husky
  HUSKY: 0
